### ISSUE TITLE
ZIP codes from E911 may be incorrect

### ISSUE THREAD

**Issue by adamfranco** [JaredOSM/vermont-address-import#7]
I noticed that in Middlebury, the E911 database has `ZIP=05740` for many addresses near the village of East Middlebury, while the USPS's ZIP code lookup service returns the main `05753` ZIP code for these addresses.

I called the Postmaster of the East Middlebury post office and he gave me the history:
> `05740` is the ZIP code that only applies to the PO boxes in the East Middlebury post office building. The East Middlebury area used to not have street delivery and all residents in that part of town had free PO boxes in the East Middlebury post office. Their mailing addresses used to have the `05740` ZIP code so that the would get routed to the post office if the street address was on the envelope instead of the PO BOX number.
> _At some point (I forgot to ask when)_ the residents petitioned to get street delivery and all street delivery in the Town of Middlebury uses the `05753` ZIP code. At this point `05740` should only be used for mail going directly to PO Boxes and not to houses.

This indicates that the E911 database does not have ZIP correct in at least this case. I've found other addresses near the New Have Town line that E911 gives as `05742` (New Haven's ZIP code), but which [usps.com](https://tools.usps.com/zip-code-lookup.htm?byaddress) lists as Middlebury's `05753`. 

At this point I do not have confidence importing ZIP codes from E911 as there may be other subtle errors like these that would be hard to tease out. Leaving `addr:postcode` blank would at least give a list of items to do follow-up work on.

**Comment by adamfranco** [comment]
If we wanted to sometimes include `addr:postcode` with this import it may be worth trying to source that from another location, such as independent research with each local postmaster unless there is only one ZIP code in E911 for the town and that ZIP code is confirmed checks against USPS.com. If E911 reports more than 1 ZIP for a town and that isn't confirmed by usps.com then I don't think we can have any confidence that the ZIP in E911 is correct.

**Comment by JaredOSM** [comment]
I agree, it probably makes sense to leave the Zip code off the import, and deal with it in a separate project in the future.
