### ISSUE TITLE
E911 doesn't include apostrophes

### ISSUE THREAD

**Issue by adamfranco** [JaredOSM/vermont-address-import#8]
Possessive apostrophes (examples [Merchant's Row](https://www.openstreetmap.org/way/519710491), [Wissler's Lane](https://www.openstreetmap.org/way/347291672)) aren't included in the E911 data set.

- [ ] Don't import duplicates if existing OSM addresses have apostrophes.

It is a better thing to have these addresses without apostrophes than to not have them at all. That said, there is also the question of where the punctuated version might be sourced and if both versions should be recorded if possible. Currently Nominatim [seems to only match the exact street](https://www.openstreetmap.org/search?query=22%20Merchants%20Row%2C%20Middlebury%2C%20VT#map=19/44.01361/-73.16799), failing if the search is a mismatch from what is in `addr:street`.

Apostrophes in addresses should probably be discussed more broadly.

**Comment by JaredOSM** [comment]
It seems like many (most?) street names (globally, not just VT) don't use an apostrophe, but I wasn't able to find a definitive reason based on a quick investigation I did a couple weeks ago.  I'll ask VCGI if there is a Vermont standard (doesn't mean it is necessarily followed by individual towns).

Looking at the street side imagery for Merchant's Row in Middlebury, the street sign doesn't appear to have an apostrophe.  Have you found any "official" source from the Town of Middlebury indicating that it should have an apostrophe?

**Comment by adamfranco** [comment]
I just check the Town's property record system and the parcel maps and property cards don't use apostrophes for `Merchants Row` but do for `WISSLER'S LANE` (which incidentally doesn't have a blade sign). More investigation is needed...

**Comment by adamfranco** [comment]
Found a couple references:

OSM-US #local-maine
https://osmus.slack.com/archives/CLVD81QJZ/p1591128917014900
> Jun 2nd, 2020 - aweech :massachusetts: [4:15 PM](https://osmus.slack.com/archives/CLVD81QJZ/p1591128917014900?thread_ts=1591128917.014900)
> Just keep in mind that the USPS has a list of unfavored characters, so those shouldn't occur in addr:street, including that apostrophe in "River's Edge Drive". https://pe.usps.com/text/pub28/28c3_019.htm


https://wiki.openstreetmap.org/wiki/Names#Watch_out_for_apostrophes
> **Watch out for apostrophes**
> If the street sign has an apostrophe, the OSM data should have an apostrophe. There is no obvious consistency; the London Underground station Barons Court is adjacent to Earl's Court, one with an apostrophe, one without.

**Comment by adamfranco** [comment]
Based on the results from a [Slack thread](https://osmus.slack.com/archives/C2VJAJCS0/p1677091707066879) and [Discourse thread](https://community.openstreetmap.org/t/apostrophes-hyphens-and-periods-in-addr-street/9201) I think we should consider apostrophes valid (and matches to E911 streets missing them) if they are mapped in OSM on streets or existing address points. The USPS and E911 exclude much valid punctuation as part of normalization, but that doesn't necessarily mean that the names don't deserve apostrophes.

**Comment by adamfranco** [comment]
As of ef1d3b39db04a9c28c7e29e16d1412e26d118c7e if OSM has apostrophes in mapped addresses these won't be considered tag conflicts with the E911 data.
